import { PROMPT_DEX_SCHEMA_VERSION, type PromptEntry } from '@/lib/tools/prompt-dex/types'

/**
 * 初期収録プロンプト(builtin)。
 *
 * SunoとUdioで「効き方」が違うため、主要ジャンルはサービス別に作り分けている。
 * - Suno: スタイル欄は4〜7語のカンマ区切り(ジャンル→テンポ→楽器→ボーカル→質感→雰囲気)。
 *   BPMは目安程度。不要な音は Style ではなく Exclude Styles 欄へ。構成は歌詞欄の [Verse]/[Chorus] タグ。
 * - Udio: 情景を文章で描写する自然言語型(セッションミュージシャンに指示する感覚)。
 *   Prompt Strength で忠実度を調整、強調したい語は繰り返す、精密制御は Manual Mode。
 *
 * 実在する存命アーティストの模倣は入れない(色・雰囲気・構成で表現)。
 * createdAt は収録順を安定させるための固定値。
 */

const D = '2026-07-22T00:00:00.000Z'

function b(
  id: string,
  e: Omit<PromptEntry, 'id' | 'createdAt' | 'updatedAt' | 'source' | 'schemaVersion'>,
): PromptEntry {
  return {
    id,
    ...e,
    createdAt: D,
    updatedAt: D,
    source: 'builtin',
    schemaVersion: PROMPT_DEX_SCHEMA_VERSION,
  }
}

// Suno/Udio共通で使い回す「サービス別のコツ」
const SUNO_TIP_STRUCTURE = '構成は歌詞欄の [Verse]/[Chorus] などのタグで指定できる'
const SUNO_TIP_EXCLUDE = '不要な音は Style欄に「no 〜」と書かず、Exclude Styles 欄へ入れる'
const SUNO_FAIL_CROWD = '語を詰め込みすぎ(8語以上)ると指定同士が競合してぼやける'
const SUNO_FAIL_BPM = 'BPMは厳密には効かず、あくまで目安として扱われる'
const UDIO_TIP_STRENGTH = 'Prompt Strength を上げると忠実度が上がり、下げると多様性が出る'
const UDIO_TIP_REPEAT = '強調したい要素は語を2回書くと効きやすい'
const UDIO_TIP_MANUAL = '細部まで固定したいときは Manual Mode(タグのみ)で作り込む'
const UDIO_FAIL_CONFLICT = '矛盾するタグ(明るい×暗い等)を混ぜると破綻しやすい'

export const BUILTIN_PROMPTS: PromptEntry[] = [
  // ===== J-POP =====
  b('bp-jpop-bright', {
    title: '【Suno】疾走感のある明るいJ-POP',
    prompt: 'bright J-pop, upbeat 128 BPM, clean electric guitar and punchy drums, clear female vocal, polished production, catchy and uplifting',
    description: '前向きで疾走感のある王道J-POP。Suno向けに要素を6語へ絞り、サビで開ける明るさを狙います。',
    genre: 'J-POP',
    subgenre: 'ポップロック',
    emotions: ['前向き', '爽やか', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['エレキギター', 'ドラム', 'シンセ'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'タイアップ'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: [
      '「catchy / uplifting」でサビが明るくまとまりやすい',
      'ジャンル→テンポ→楽器→ボーカルの順で並べると各指定が効く',
    ],
    failurePoints: [SUNO_FAIL_CROWD, SUNO_FAIL_BPM],
    adjustments: [
      SUNO_TIP_STRUCTURE + '(サビは [Chorus] を明示)',
      '声を柔らかくしたいときは clear female vocal を warm female vocal に変える',
    ],
    tags: ['王道', 'サビ映え', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-jpop-bright-udio', {
    title: '【Udio】疾走感のある明るいJ-POP',
    prompt:
      'An upbeat, uplifting modern J-pop song with driving energy — bright clean electric guitars, punchy live drums, sparkling synths, and a clear emotive female lead vocal. Polished radio-ready production, big catchy chorus, hopeful and energetic mood.',
    description: 'Udio向けに情景を文章で描写した明るいJ-POP。Prompt Strengthを高めにすると狙いへ寄ります。',
    genre: 'J-POP',
    subgenre: 'ポップロック',
    emotions: ['前向き', '爽やか', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['エレキギター', 'ドラム', 'シンセ'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'タイアップ'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: [
      '「big catchy chorus」を文章に入れるとサビの押しが出る',
      UDIO_TIP_STRENGTH,
    ],
    failurePoints: [UDIO_FAIL_CONFLICT, 'Prompt Strength が低いと prompt から離れて平凡になる'],
    adjustments: [
      UDIO_TIP_REPEAT + '(例: catchy を2回)',
      '明るさを足すなら bright / sparkling を、落ち着けるなら mellow を加える',
    ],
    tags: ['王道', 'サビ映え', 'Udio向け'],
    version: 'v1',
  }),

  // ===== バラード =====
  b('bp-jpop-ballad', {
    title: '【Suno】泣けるピアノバラード',
    prompt: 'emotional pop ballad, slow 68 BPM, grand piano and warm strings, soft female vocal, spacious reverb, heartfelt and nostalgic',
    description: '静かに始まり後半で盛り上げる泣かせ系バラード。Suno向けに6語構成。歌詞を届けたいときに。',
    genre: 'バラード',
    subgenre: 'ピアノバラード',
    emotions: ['切ない', '感動的', 'ノスタルジック'],
    bpm: 'slow',
    vocal: 'female',
    instruments: ['ピアノ', 'ストリングス'],
    era: '2010s',
    uses: ['MV', '結婚式', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: [
      'ピアノ+ストリングスは安定して「泣ける」質感になりやすい',
      'slow 68 BPM で歌詞が聴き取りやすくなる',
    ],
    failurePoints: ['reverbが強いと言葉がぼやける', SUNO_FAIL_BPM],
    adjustments: [
      'ラスサビを厚くするなら [Chorus: soaring vocals, swelling strings] と : で指定',
      SUNO_TIP_EXCLUDE + '(打ち込み感を消すなら drums を除外)',
    ],
    tags: ['バラード', '泣ける', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-ballad-udio', {
    title: '【Udio】壮大なピアノバラード',
    prompt:
      'A heartfelt, cinematic piano ballad that starts intimate and swells to a powerful climax — gentle grand piano, warm swelling strings, subtle pads, and a soft emotive female vocal. Nostalgic and moving, with spacious natural reverb and dynamic build.',
    description: 'Udio向けに「静→大」の展開を文章で描いたバラード。忠実度が高く、盛り上がりを作りやすい構成です。',
    genre: 'バラード',
    subgenre: 'ピアノバラード',
    emotions: ['切ない', '感動的', 'ノスタルジック'],
    bpm: 'slow',
    vocal: 'female',
    instruments: ['ピアノ', 'ストリングス'],
    era: '2010s',
    uses: ['MV', '結婚式', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: [
      '「starts intimate and swells to a climax」で山を作れる',
      'Udioは音質が滑らかで、生ピアノ+ストリングスが映える',
    ],
    failurePoints: ['盛り込みすぎると静けさが失われる', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_STRENGTH, '言葉を立てたいときは intimate / vulnerable を強調する'],
    tags: ['バラード', '泣ける', 'Udio向け'],
    version: 'v1',
  }),

  // ===== ロック =====
  b('bp-rock-band', {
    title: '【Suno】骨太なバンドロック',
    prompt: 'driving alternative rock, fast 150 BPM, distorted guitars and powerful drums, prominent bass, raw male vocal, live band energy',
    description: 'ライブ感のある骨太ロック。Suno向けに編成を名指しして生バンド感を安定させます。',
    genre: 'ロック',
    subgenre: 'オルタナ',
    emotions: ['熱い', '力強い', '疾走感'],
    bpm: 'fast',
    vocal: 'male',
    instruments: ['エレキギター', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'ライブ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: [
      '「live band energy」で打ち込み臭さが減る',
      'guitars/bass/drums を名指しするとバンド編成が安定',
    ],
    failurePoints: ['distortionを強調しすぎると歌が埋もれる', SUNO_FAIL_CROWD],
    adjustments: [
      'サビを厚くするなら [Chorus: double-tracked guitars] と指定',
      '歌を前に出したいときは production を balanced に寄せる',
    ],
    tags: ['バンド', 'ギター', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-rock-udio', {
    title: '【Udio】ライブ感のあるロック',
    prompt:
      'A raw, high-energy alternative rock song that feels like a live band in a room — crunchy distorted electric guitars, a driving rhythm section with punchy drums and a thick bass line, and a gritty passionate male vocal. Loud, dynamic, and anthemic.',
    description: 'Udio向けに「ライブの一室」の空気感を描写したロック。生々しい質感が得意なUdioと相性◎。',
    genre: 'ロック',
    subgenre: 'オルタナ',
    emotions: ['熱い', '力強い', '疾走感'],
    bpm: 'fast',
    vocal: 'male',
    instruments: ['エレキギター', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'ライブ', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: [
      '「live band in a room」で生っぽい空気が出る',
      'Udioは歪みやアタックの質感が自然に出やすい',
    ],
    failurePoints: ['gritty を盛りすぎるとボーカルが荒れる', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_REPEAT + '(driving を繰り返すと疾走感が増す)', UDIO_TIP_MANUAL],
    tags: ['バンド', 'ギター', 'Udio向け'],
    version: 'v1',
  }),

  // ===== アニソン =====
  b('bp-anison-op', {
    title: '【Suno】アニメOP風の高揚アニソン',
    prompt: 'anime opening, high energy 175 BPM, fast drums and bright synth leads, orchestral hits, powerful female vocal, soaring epic chorus',
    description: '90秒で映えるアニメOP的な高揚感。Suno向けに要素を絞り、前奏→サビの爆発を狙います。',
    genre: 'アニソン',
    subgenre: 'OP/主題歌',
    emotions: ['高揚', '前向き', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'ドラム', 'オーケストラヒット'],
    era: '2020s',
    uses: ['MV', 'Shorts', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「soaring epic chorus」でOPらしい爆発力が出る', 'orchestral hits が疾走感に厚みを足す'],
    failurePoints: [SUNO_FAIL_CROWD, 'テンポが速く歌詞が詰め込み気味になりがち'],
    adjustments: [
      'サビ手前に [Pre-Chorus] を置いて溜めを作る',
      SUNO_TIP_STRUCTURE,
    ],
    tags: ['アニソン', '高揚', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-anison-udio', {
    title: '【Udio】疾走するアニソンOP',
    prompt:
      'A fast, energetic anime opening theme with a soaring, epic chorus — driving double-kick drums, bright synth leads, dramatic orchestral hits, and a powerful female lead vocal. Cinematic, uplifting, and triumphant, building to a huge hook.',
    description: 'Udio向けに構築感を文章で描いたアニソンOP。オーケストラ×バンドの厚みを出したいときに。',
    genre: 'アニソン',
    subgenre: 'OP/主題歌',
    emotions: ['高揚', '前向き', 'エモい'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'ドラム', 'オーケストラヒット'],
    era: '2020s',
    uses: ['MV', 'Shorts', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「building to a huge hook」でサビへの流れが作れる', 'Udioは厚いレイヤーを破綻なくまとめやすい'],
    failurePoints: ['要素が多く音が団子になりやすい', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_STRENGTH, 'サビだけ強めたいなら epic / soaring を繰り返す'],
    tags: ['アニソン', '高揚', 'Udio向け'],
    version: 'v1',
  }),

  // ===== Lo-fi =====
  b('bp-lofi-study', {
    title: '【Suno】作業がはかどるLo-fiビート',
    prompt: 'lo-fi hip hop, chill 82 BPM, mellow piano and dusty drums, warm bass, instrumental, vinyl crackle, relaxed and nostalgic',
    description: '勉強・作業向けの主張しないLo-fi。Suno向けに歌なし指定を明確化。長時間流しても疲れません。',
    genre: 'Lo-fi',
    subgenre: 'チルホップ',
    emotions: ['落ち着く', 'ノスタルジック', '穏やか'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['ピアノ', 'ドラム', 'ベース'],
    era: '2020s',
    uses: ['作業用BGM', 'YouTube', '配信'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['vinyl crackle でLo-fiらしさが一気に出る', '「instrumental」明記で作業の邪魔をしない'],
    failurePoints: ['メロが強すぎると作業用から外れる', SUNO_FAIL_BPM],
    adjustments: [
      '歌なしを確実にするなら Instrumental を ON にし、Exclude に vocals を入れる',
      '眠くしたくないときは 82→90 BPM へ上げる',
    ],
    tags: ['作業用', 'チル', 'インスト', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-lofi-udio', {
    title: '【Udio】夜のLo-fiインスト',
    prompt:
      'A warm, hazy lo-fi hip hop instrumental for a late night — mellow Rhodes piano, dusty boom-bap drums, soft upright bass, vinyl crackle and tape hiss. Relaxed, nostalgic, and cozy, with a laid-back groove and no vocals.',
    description: 'Udio向けに夜の空気を描写したLo-fi。テープ質感まで文章で指定でき、雰囲気が濃く出ます。',
    genre: 'Lo-fi',
    subgenre: 'チルホップ',
    emotions: ['ノスタルジック', '穏やか', '大人っぽい'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['エレピ', 'ドラム', 'ベース'],
    era: '2020s',
    uses: ['作業用BGM', 'YouTube', '配信'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「tape hiss / vinyl crackle」で質感が濃く出る', 'Udioは滑らかな音で長尺BGM化しやすい'],
    failurePoints: ['展開を付けすぎると作業の邪魔になる', 'Prompt Strength が低いとメロが立ちすぎる'],
    adjustments: ['歌なしを保つため no vocals を明記し繰り返す', UDIO_TIP_STRENGTH],
    tags: ['作業用', 'チル', '夜', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-lofi-shorts', {
    title: '【Suno】Shorts映えするチルフック',
    prompt: 'chill lo-fi pop, 90 BPM, mellow keys and boom-bap drums, soft female vocal, catchy short hook, warm and loopable',
    description: '冒頭にフックを置いた短尺向けLo-fi。ShortsやTikTokでループ再生されやすい構成を狙います。',
    genre: 'Lo-fi',
    subgenre: 'チルポップ',
    emotions: ['穏やか', 'かわいい', '落ち着く'],
    bpm: 'mid',
    vocal: 'female',
    instruments: ['キーボード', 'ドラム'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'ループ'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「catchy short hook / loopable」で冒頭離脱を減らせる', '短いフックが繰り返しに向く'],
    failurePoints: ['イントロが長いとShortsで飛ばされる', SUNO_FAIL_BPM],
    adjustments: ['歌詞の先頭に [Chorus] を置いてサビ始まりにする', '15〜30秒で完結するよう展開を絞る'],
    tags: ['Shorts', 'ループ', 'フック', 'チル', 'Suno向け'],
    version: 'v1',
  }),

  // ===== EDM =====
  b('bp-edm-festival', {
    title: '【Suno】フェス映えEDMアンセム',
    prompt: 'festival EDM anthem, big room 128 BPM, huge supersaw drop and punchy kick, sidechain pump, energetic female vocal, euphoric and wide',
    description: 'ドロップを主役にしたフェス系EDM。Suno向けにbuild→dropの語で高揚を狙います。',
    genre: 'EDM',
    subgenre: 'ビッグルーム',
    emotions: ['高揚', '爽快', 'パワフル'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'キック'],
    era: '2010s',
    uses: ['MV', 'クラブ', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['sidechain pump でEDMらしいうねりが出る', '「euphoric / wide」で高揚感が乗る'],
    failurePoints: ['ドロップが濁ると爆発力が半減', 'ボーカルとシンセが同帯で干渉しやすい'],
    adjustments: ['歌詞に [Build-up] → [Drop] を置いてメリハリを付ける', SUNO_TIP_EXCLUDE],
    tags: ['EDM', 'ドロップ', '高揚', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-edm-udio', {
    title: '【Udio】高揚するEDMアンセム',
    prompt:
      'A euphoric festival EDM anthem with a massive drop — soaring supersaw synths, a punchy four-on-the-floor kick, heavy sidechain pumping, and an energetic female topline. Big build-up into an explosive, wide, hands-in-the-air chorus. Bright and powerful.',
    description: 'Udio向けにbuild→dropの流れを文章で描いたEDM。高揚のピークを言葉で作り込めます。',
    genre: 'EDM',
    subgenre: 'ビッグルーム',
    emotions: ['高揚', '爽快', 'パワフル'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'キック'],
    era: '2010s',
    uses: ['MV', 'クラブ', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「big build-up into an explosive chorus」でメリハリが出る', 'Udioは太いシンセを破綻なく鳴らしやすい'],
    failurePoints: ['要素過多でドロップが渋滞する', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_REPEAT + '(euphoric を繰り返す)', '刺さりを抑えるなら bright を warm に'],
    tags: ['EDM', 'ドロップ', '高揚', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-future-bass', {
    title: '【Suno】きらめくフューチャーベース',
    prompt: 'future bass, 150 BPM half-time, lush supersaw chords, pitched vocal chops, soft female vocal, punchy drums, shimmering and emotional',
    description: 'きらびやかで感情的なフューチャーベース。Suno向けにchops＋chordsで透明感を出します。',
    genre: 'EDM',
    subgenre: 'フューチャーベース',
    emotions: ['エモい', '透明感', '高揚'],
    bpm: 'fast',
    vocal: 'female',
    instruments: ['シンセ', 'ボーカルチョップ', 'ドラム'],
    era: '2020s',
    uses: ['MV', 'YouTube', 'Shorts'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['vocal chops+lush chords で「きらめき」が出る', 'half-time で疾走と重さのバランスが取れる'],
    failurePoints: ['コードが厚すぎるとボーカルが埋もれる', '高音が刺さり聴き疲れしやすい'],
    adjustments: ['ボーカルを立てるなら lush chords を soft chords に', SUNO_TIP_EXCLUDE],
    tags: ['きらめき', 'エモい', 'ドロップ', 'Suno向け'],
    version: 'v1',
  }),

  // ===== ゲーム音楽 =====
  b('bp-game-battle', {
    title: '【Suno】ゲームのバトル曲(オーケストラ)',
    prompt: 'epic orchestral battle theme, fast 140 BPM, driving strings and powerful brass, taiko and orchestral percussion, choir swells, instrumental, cinematic and intense',
    description: '緊張感のあるボス戦向けインスト。Suno向けに和洋の打楽器を指定して迫力を出します。',
    genre: 'ゲーム音楽',
    subgenre: 'オーケストラ',
    emotions: ['緊張感', '壮大', '力強い'],
    bpm: 'fast',
    vocal: 'instrumental',
    instruments: ['ストリングス', 'ブラス', 'パーカッション'],
    era: 'timeless',
    uses: ['ゲーム', 'BGM', '配信'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「cinematic / intense」で緊張感が出る', 'taiko+choir で和洋折衷の迫力が作れる'],
    failurePoints: ['要素が多くミックスが団子になりやすい', 'ループ用途だと展開が付きすぎる'],
    adjustments: ['ループ化するなら seamless loop, minimal development を足す', SUNO_TIP_EXCLUDE + '(歌なしは vocals を除外)'],
    tags: ['ゲーム', 'オーケストラ', 'インスト', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-game-udio', {
    title: '【Udio】壮大なゲームのバトル曲',
    prompt:
      'An intense, cinematic orchestral battle theme for a video game boss fight — relentless staccato strings, heroic brass stabs, thunderous taiko and orchestral percussion, and dramatic choir swells. Dark, epic, and driving, with a sense of rising danger. Instrumental, no vocals.',
    description: 'Udio向けに緊迫感を文章で描いたバトル曲。厚いオーケストラを滑らかにまとめたいときに。',
    genre: 'ゲーム音楽',
    subgenre: 'オーケストラ',
    emotions: ['緊張感', '壮大', '力強い'],
    bpm: 'fast',
    vocal: 'instrumental',
    instruments: ['ストリングス', 'ブラス', 'パーカッション'],
    era: 'timeless',
    uses: ['ゲーム', 'BGM', '配信'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「rising danger」で緊迫の高まりが作れる', 'Udioは大編成でも音が濁りにくい'],
    failurePoints: ['盛り込みすぎて主旋律が埋もれる', UDIO_FAIL_CONFLICT],
    adjustments: [UDIO_TIP_MANUAL, 'ループ用途なら seamless, minimal development を明記して繰り返す'],
    tags: ['ゲーム', 'オーケストラ', 'インスト', 'Udio向け'],
    version: 'v1',
  }),
  b('bp-game-chiptune', {
    title: '【Suno】レトロなチップチューン',
    prompt: 'upbeat chiptune, 8-bit, 145 BPM, square and pulse leads, arpeggios, noise percussion, instrumental, playful and nostalgic',
    description: 'レトロゲーム風の8bitインスト。Suno向けに音源名を指定してレトロ感を確実に出します。',
    genre: 'ゲーム音楽',
    subgenre: 'チップチューン',
    emotions: ['楽しい', 'ノスタルジック', 'かわいい'],
    bpm: 'fast',
    vocal: 'instrumental',
    instruments: ['シンセ(8bit)', 'アルペジオ'],
    era: 'retro',
    uses: ['ゲーム', 'BGM', 'Shorts'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「8-bit / square lead」でレトロ感が確実に出る', 'アルペジオが手軽に賑やかさを足す'],
    failurePoints: ['音色が単調で長尺だと飽きやすい', 'ベースが弱いと軽くなりすぎる'],
    adjustments: ['厚みが欲しいときは bass line, drums を足す', '少しリッチにするなら 8-bit を 16-bit chiptune に'],
    tags: ['チップチューン', 'レトロ', 'インスト', 'Suno向け'],
    version: 'v1',
  }),

  // ===== 作業用BGM =====
  b('bp-ambient-focus', {
    title: '【Suno】集中できるアンビエントピアノ',
    prompt: 'ambient piano, minimal, very slow 60 BPM, soft felt piano, airy pads, gentle textures, instrumental, calm and focused',
    description: '深い集中・睡眠導入向けの静かなインスト。Suno向けに「no drums」ではなくExcludeで抜きます。',
    genre: '作業用BGM',
    subgenre: 'アンビエント',
    emotions: ['静か', '落ち着く', '癒し'],
    bpm: 'slow',
    vocal: 'instrumental',
    instruments: ['ピアノ', 'パッド'],
    era: '2020s',
    uses: ['作業用BGM', '睡眠', '瞑想'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['felt piano の柔らかさが長時間でも疲れにくい', '「minimal / calm」で集中の邪魔をしない'],
    failurePoints: ['展開を付けすぎると集中が切れる', 'パッドが厚すぎると眠すぎ/重すぎになる'],
    adjustments: ['リズムを消すなら drums / beat を Exclude Styles へ', '眠らせたくないときは 60→72 BPM へ'],
    tags: ['作業用', '睡眠', 'ピアノ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-ambient-udio', {
    title: '【Udio】癒しのアンビエント',
    prompt:
      'A calm, minimal ambient piece for deep focus and relaxation — soft felt piano, airy evolving pads, gentle field-recording textures, and warm reverb. Spacious, weightless, and soothing, with no drums and no vocals. Slow and meditative.',
    description: 'Udio向けに静けさを文章で描いたアンビエント。空間の広がりを言葉で作り込めます。',
    genre: '作業用BGM',
    subgenre: 'アンビエント',
    emotions: ['静か', '落ち着く', '癒し'],
    bpm: 'slow',
    vocal: 'instrumental',
    instruments: ['ピアノ', 'パッド'],
    era: '2020s',
    uses: ['作業用BGM', '睡眠', '瞑想'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「spacious / weightless」で広がりが出る', 'Udioは長い持続音を滑らかに保てる'],
    failurePoints: ['要素を足すと静けさが崩れる', 'Prompt Strength が低いとリズムが混ざることがある'],
    adjustments: ['「no drums / no vocals」を明記し繰り返す', UDIO_TIP_STRENGTH],
    tags: ['作業用', '睡眠', 'ピアノ', 'Udio向け'],
    version: 'v1',
  }),

  // ===== Shorts向け =====
  b('bp-shorts-hook', {
    title: '【Suno】Shorts向けフック先行ポップ',
    prompt: 'catchy pop, hook-first, upbeat 118 BPM, bright synth and punchy claps, bright female vocal, simple arrangement, high-energy intro',
    description: '最初の2秒で掴む短尺特化ポップ。Suno向けに構成をシンプルに保ち歌を主役にします。',
    genre: 'Shorts向け',
    subgenre: 'ポップ',
    emotions: ['楽しい', '前向き', 'キャッチー'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['シンセ', 'クラップ'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'YouTube'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「hook-first / high-energy intro」で冒頭離脱に強い', 'シンプル編成で歌が主役になる'],
    failurePoints: ['サビが弱いと最後まで見られない', SUNO_FAIL_CROWD],
    adjustments: ['歌詞は [Chorus] から始めてフックを最前面に', 'ループ向けに終わりを頭とつなげる'],
    tags: ['Shorts', 'フック', 'キャッチー', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-shorts-udio', {
    title: '【Udio】Shorts向けフック先行ポップ',
    prompt:
      'A catchy, high-energy pop song built around an instantly memorable hook that hits in the first two seconds — bright plucky synths, punchy claps, and a bright confident female vocal. Simple, punchy arrangement, loopable, vertical-video friendly. Fun and upbeat.',
    description: 'Udio向けに「冒頭2秒で掴む」設計を文章化したShorts用ポップ。掴みの強さを言葉で作れます。',
    genre: 'Shorts向け',
    subgenre: 'ポップ',
    emotions: ['楽しい', '前向き', 'キャッチー'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['シンセ', 'クラップ'],
    era: '2020s',
    uses: ['Shorts', 'TikTok', 'YouTube'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「hook that hits in the first two seconds」で掴みが強い', UDIO_TIP_REPEAT + '(catchy を繰り返す)'],
    failurePoints: ['編成が寂しいと尺が持たない', 'Prompt Strength が低いとフックがぼやける'],
    adjustments: ['ループ用に loopable を明記', UDIO_TIP_STRENGTH],
    tags: ['Shorts', 'フック', 'キャッチー', 'Udio向け'],
    version: 'v1',
  }),

  // ===== インストゥルメンタル =====
  b('bp-acoustic-inst', {
    title: '【Suno】優しいアコースティックギター',
    prompt: 'warm acoustic guitar, 92 BPM, fingerpicked steel-string guitar, light percussion, soft upright bass, instrumental, gentle and heartfelt',
    description: '素朴で温かいアコースティックのインスト。Suno向けに奏法を指定して生っぽさを出します。',
    genre: 'インストゥルメンタル',
    subgenre: 'アコースティック',
    emotions: ['穏やか', '温かい', '癒し'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['アコースティックギター', 'ベース', 'パーカッション'],
    era: 'timeless',
    uses: ['BGM', 'Vlog', '作業用BGM'],
    services: ['Suno'],
    beginnerFriendly: true,
    successPoints: ['「fingerpicked」で生っぽい表情が出る', '編成が薄めで映像の邪魔をしない'],
    failurePoints: ['同じフレーズの繰り返しで単調になりやすい', 'パーカッションが強いと素朴さが減る'],
    adjustments: ['変化が欲しいときは中盤に piano を足す', 'より静かにするなら percussion を Exclude へ'],
    tags: ['アコギ', '癒し', 'インスト', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-acoustic-udio', {
    title: '【Udio】温かいアコースティックインスト',
    prompt:
      'A warm, intimate acoustic instrumental with an organic, in-the-room feel — gently fingerpicked steel-string guitar, soft upright bass, light hand percussion, and a touch of piano. Heartfelt, cozy, and unhurried, with natural room ambience. No vocals.',
    description: 'Udio向けに「部屋の空気」を描いたアコースティック。生録りのような温もりが得意です。',
    genre: 'インストゥルメンタル',
    subgenre: 'アコースティック',
    emotions: ['穏やか', '温かい', '癒し'],
    bpm: 'mid',
    vocal: 'instrumental',
    instruments: ['アコースティックギター', 'ベース', 'ピアノ'],
    era: 'timeless',
    uses: ['BGM', 'Vlog', '作業用BGM'],
    services: ['Udio'],
    beginnerFriendly: true,
    successPoints: ['「in-the-room feel / room ambience」で生録り感が出る', 'Udioは生楽器の質感を自然に再現しやすい'],
    failurePoints: ['要素を足すと素朴さが薄れる', 'Prompt Strength が低いと歌が入ることがある'],
    adjustments: ['歌なしを保つため no vocals を明記', UDIO_TIP_STRENGTH],
    tags: ['アコギ', '癒し', 'インスト', 'Udio向け'],
    version: 'v1',
  }),

  // ===== シティポップ =====
  b('bp-citypop', {
    title: '【Suno】ナイトドライブなシティポップ',
    prompt: 'city pop, groovy 110 BPM, funky electric bass and clean guitar, warm electric piano, smooth female vocal, tasteful sax, nostalgic 80s night vibe',
    description: '夜の都会を思わせるシティポップ。Suno向けに要素を絞りつつ80sの空気を出します。',
    genre: 'シティポップ',
    subgenre: 'ファンク寄り',
    emotions: ['ノスタルジック', 'おしゃれ', '穏やか'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['ベース', 'エレピ', 'サックス'],
    era: '80s',
    uses: ['MV', 'YouTube', '作業用BGM'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「night vibe / electric piano」で世界観が決まる', 'funky bass がグルーヴの土台になる'],
    failurePoints: ['sax を盛ると古臭くなりすぎる', 'グルーヴが甘いと平坦に聞こえる'],
    adjustments: ['古さが気になるなら sax を控え guitar を前へ', SUNO_FAIL_BPM + '(ノリは tight groove の語で補う)'],
    tags: ['シティポップ', '夜', 'おしゃれ', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-citypop-udio', {
    title: '【Udio】ナイトドライブなシティポップ',
    prompt:
      'A groovy, nostalgic 80s city pop track that feels like a night drive through neon-lit streets — funky electric bass, clean chorus guitar, warm electric piano, tasteful sax licks, and a smooth female vocal. Sophisticated, mellow, and stylish, with a lush chorus.',
    description: 'Udio向けにネオンの情景を描いたシティポップ。おしゃれなグルーヴを言葉で作り込めます。',
    genre: 'シティポップ',
    subgenre: 'ファンク寄り',
    emotions: ['ノスタルジック', 'おしゃれ', '穏やか'],
    bpm: 'upper',
    vocal: 'female',
    instruments: ['ベース', 'エレピ', 'サックス'],
    era: '80s',
    uses: ['MV', 'YouTube', '作業用BGM'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「night drive / neon-lit streets」で世界観が濃く出る', 'Udioはグルーヴと質感を両立しやすい'],
    failurePoints: ['sax を盛りすぎると古臭くなる', UDIO_FAIL_CONFLICT],
    adjustments: ['ノリを強めるなら tight groove, syncopation を繰り返す', UDIO_TIP_STRENGTH],
    tags: ['シティポップ', '夜', 'おしゃれ', 'Udio向け'],
    version: 'v1',
  }),

  // ===== R&B =====
  b('bp-rnb-soul', {
    title: '【Suno】しっとりR&B/ソウルバラード',
    prompt: 'smooth R&B soul, slow 72 BPM, warm Rhodes piano and mellow bass, brushed drums, soulful male vocal, gospel-tinged harmonies, intimate and silky',
    description: '大人っぽくしっとりしたR&B。Suno向けに声の表情を主役にした落ち着いた構成です。',
    genre: 'R&B',
    subgenre: 'ソウル',
    emotions: ['大人っぽい', '切ない', '穏やか'],
    bpm: 'slow',
    vocal: 'male',
    instruments: ['エレピ', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Suno'],
    beginnerFriendly: false,
    successPoints: ['「soulful vocal / gospel harmonies」で表情が豊かに', 'Rhodes+brushed drums で大人の落ち着きが出る'],
    failurePoints: ['コーラスを盛りすぎると主役の声がぼやける', 'テンポが遅く間延びしやすい'],
    adjustments: ['間延びするなら軽いビートを前に出す', '声を立てるなら harmonies を [Chorus: subtle harmonies] に'],
    tags: ['R&B', '大人', 'しっとり', 'Suno向け'],
    version: 'v1',
  }),
  b('bp-rnb-udio', {
    title: '【Udio】官能的なR&Bソウル',
    prompt:
      'A smooth, sensual slow-jam R&B soul ballad — warm Rhodes piano, mellow rounded bass, soft brushed drums, and an intimate soulful male vocal with gospel-tinged backing harmonies. Silky, late-night, and emotional, with a warm, rich mix.',
    description: 'Udio向けに夜の艶を描いたR&B。声とハーモニーの質感を滑らかに再現したいときに。',
    genre: 'R&B',
    subgenre: 'ソウル',
    emotions: ['大人っぽい', '切ない', '穏やか'],
    bpm: 'slow',
    vocal: 'male',
    instruments: ['エレピ', 'ベース', 'ドラム'],
    era: '2010s',
    uses: ['MV', 'YouTube', 'BGM'],
    services: ['Udio'],
    beginnerFriendly: false,
    successPoints: ['「silky / late-night」で艶のある空気が出る', 'Udioは声とハモの質感を滑らかに保てる'],
    failurePoints: ['ハーモニーが厚いと主役の声が沈む', 'テンポが遅く間延びしやすい'],
    adjustments: ['声を立てたいときは backing harmonies を subtle にして繰り返す', UDIO_TIP_STRENGTH],
    tags: ['R&B', '大人', 'しっとり', 'Udio向け'],
    version: 'v1',
  }),
]
